server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

spring:
  security:
    user:
      name: user
      password: password
    oauth2:
      authorization server:
        client:
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/oidc-client"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true



  application:
    name: authsphere-application

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Prathm#23

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  redis:
      host: localhost
      port: 6379
      timeout: 60000

  mail:
    host: smtp.gmail.com
    port: 587
    username: indulkarprathmesh7@gmail.com
    password: pass  # from Gmail App Passwords
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true



#public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzMuX4co3ovnhnV950HD1GOyAhXVfazDU720MzdZ4OZmWJFHuiJeKESDE+TuV/D54PtIxyxI4o6sGKq4Ul36tyAV6kK/UJCs4BVncpR6IxLKscUa0DOMsmSErrvgIccQ+J5Vrd7Vj72Uu5EEM1mnj3oLcIR1OMSnnnUto9iITuWRmhrhUlkn8vdSjiIHargagzz15jMP+3KSzHoitaEjuqRsPDJLc9557Fd+Se90s84v6RwYdcRTyGTFqy5pYhqGONs60JoPAPCCcSStEoaQ6lM/ib7c84trlcVDLNRz3iQzx9TqpLy5vkkfxZG38FHxyslz1ep7/nc4M9rRGn3UFCwIDAQAB
#private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDMy5fhyjei+eGdX3nQcPUY7ICFdV9rMNTvbQzN1ng5mZYkUe6Il4oRIMT5O5X8Png+0jHLEjijqwYqrhSXfq3IBXqQr9QkKzgFWdylHojEsqxxRrQM4yyZISuu+AhxxD4nlWt3tWPvZS7kQQzWaePegtwhHU4xKeedS2j2IhO5ZGaGuFSWSfy91KOIgdquBqDPPXmMw/7cpLMeiK1oSO6pGw8Mktz3nnsV35J73Szzi/pHBh1xFPIZMWrLmliGoY42zrQmg8A8IJxJK0ShpDqUz+Jvtzzi2uVxUMs1HPeJDPH1OqkvLm+SR/FkbfwUfHKyXPV6nv+dzgz2tEafdQULAgMBAAECggEAAc7eDUD8sr2PwoyqXDh3rewnKw1H3AKyxeSg3fBSN2NKAuuhtP9VrdweTP4TAx8zY9+ePyhbzWFEIjFqg/9WRDpBF3TtRF68gPoO/TP0gGEB92c1DFBK4stta/Q95pa4wN2K7MS74HeoQb2+xfYjZAEhnRphRVZsJr0DCB/Trub4RKUdlQOqvAyc+LrruwjdyJcMqy9l1dpcOyHBMMaGneKWBUy8P126E9wxEGhhAfUKVCVE8pFXAwi3ZFAF32jAaqIhMrFQ/JzHpFZeOUiAnjIReJzF/n3wZDpvibwlCO1vY/kc0q2dwXKOA+J4FyqLAzJ085DfpDMPKStTc0vFWQKBgQD72sP8+Xa7XDYSDLtLvhnV9eawy87h1JHJVpm7a6llAhFRTfxhcaC05p5DC5lpp6VjJ4IRTeMG1X/qC7wISW4dDYfwED+gTX9T+1OnttVWkfIqi4ZdXNQHlpR7H+AkeLLX/iwTX3+tFxrF7LZG3k8lK1zCyD1okERhjgcO94JnMwKBgQDQKoj344PmqQhwdYVQwY/nR1rn5z8TsfhNIH1JtENwj+YjVLKmnKgY1ykaiDgt3HH5clYU5fy79cUEbd7mWx1GTzFsq5WFSaVRDdH2E+b9s/LtyhdxKtjtfeiXAV6GENhntfb8Zlx3aD6mD3fbRb1ogknnDEPYY5pXgKxXPc4KyQKBgDyuErZqrG6r4uMqah3vqW3hlzlVgXzrqExoLxX29JM/kkiSj5IyvFOZlNv2eXn5SGHBbRcaOu60leMf/KfKeVtKnUv7vjizM1Bap2crJ+95rm0NvMvVx8gkQZYAshJXek+MD7aDNdHQVUUGqUwd19fOwMS1VgZRbAhNHeo/PA39AoGAEnhjtNMMJhBDfm7/CD5UfWn4Z/E9yIqXBIjodPy4qykpe2MNgvkNdT7KF9+UVIVl24NIngwWE7tn4s+44mmdPFrUgNbsqmnxcDKwuYvkiAhKeszerZzmqJPuak+lynF+Mh2UL6sJc1LdlDB1KxCSEM7WrdiJwI596Fuzbv495PkCgYBNiPGwuDsfUQsKo0Xd+nzfkKC1Z/Y2fyJuOsqmXwYwUN4urujc2BD+i5GTvZ6vsrtrZ1aiyqju04+SJkozb4xCQ8PKveu/gBg2zEk3iU9CqpmFX8dtyRhD3u7rwSZPFY0+drhm7SrzxLYzADBW4+0uPa8tfWFXkpIPe+Ikl066ew==0
